name: CI/CD
on:
  pull_request:
  push:
    branches:
      - main
    tags-ignore:
      - "v*-prerelease+*" # excludes v1.2.3-prerelease+3

jobs:
  integrate:
    name: Integrate
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.prepare.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
          fetch-depth: "0"

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Setup dependencies
        run: go mod download

      - name: Test
        run: make test

      - name: Calculate prerelease version
        id: semver
        uses: paulhatch/semantic-version@v5.4.0
        if: github.ref == 'refs/heads/main'
        with:
          tag_prefix: v
          major_pattern: "#major"
          minor_pattern: "#minor"
          version_format: "v${major}.${minor}.${patch}-prerelease+${increment}"
          search_commit_body: true

      - name: Prepare
        id: prepare
        run: |
          # Change the version based on the branch
          if [[ "${{ github.ref}}" == "refs/heads/main" ]]; then
            # Use the prerelease version when building from main
            echo "version=${{ steps.semver.outputs.version }}" >> "$GITHUB_OUTPUT"
            echo "version_with_sha=${{ steps.semver.outputs.version }} (${{ github.sha }})" >> "$GITHUB_OUTPUT"
          else
            # Use the actual version when building from a tag
            echo "version=${{ github.ref_name }}" >> "$GITHUB_OUTPUT"
            echo "version_with_sha=${{ github.ref_name }} (${{ github.sha }})" >> "$GITHUB_OUTPUT"
          fi

      - name: Build
        env:
          VERSION: ${{ steps.prepare.outputs.version_with_sha }}
        run: |
          GOOS=darwin  GOARCH=amd64  BIN=tmpl-darwin-amd64  make build
          GOOS=darwin  GOARCH=arm64  BIN=tmpl-darwin-arm64  make build
          GOOS=linux   GOARCH=amd64  BIN=tmpl-linux-amd64   make build
          GOOS=linux   GOARCH=arm64  BIN=tmpl-linux-arm64   make build
          ls -lh bin

      - name: Checksum
        run: |
          cd bin
          sha256sum tmpl-* > checksums.txt
          sha256sum --check checksums.txt

      - name: Run
        run: |
          test_command() { echo "--------------"; echo "Testing: $1"; eval $1 || exit 1; }
          test_command "bin/tmpl-linux-amd64 --version"
          test_command "bin/tmpl-linux-amd64 --help"
          test_command "bin/tmpl-linux-amd64 generate --help"
          test_command "bin/tmpl-linux-amd64 license"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            bin/tmpl-*
            bin/checksums.txt
            LICENSE

      - name: Tag commit version
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -a ${{ steps.prepare.outputs.version }} -m "${{ steps.prepare.outputs.version }}"
          git push origin ${{ steps.prepare.outputs.version }}

  release:
    name: Release
    needs: integrate
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts

      - name: Draft a release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          draft: true
          files: |
            bin/tmpl-*
            bin/checksums.txt
            LICENSE

  image:
    name: Image
    needs: integrate
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/jeremybower/tmpl
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
          fetch-depth: "0"

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts

      - name: Build image
        env:
          VERSION: ${{ needs.integrate.outputs.version }}
        run: |
          BIN=tmpl-darwin-amd64  IMAGE=${{ env.IMAGE }}  SUFFIX=-darwin-amd64  TARGETPLATFORM=darwin/amd64  make image
          BIN=tmpl-darwin-arm64  IMAGE=${{ env.IMAGE }}  SUFFIX=-darwin-arm64  TARGETPLATFORM=darwin/arm64  make image
          BIN=tmpl-linux-amd64   IMAGE=${{ env.IMAGE }}  SUFFIX=-linux-amd64   TARGETPLATFORM=linux/amd64   make image
          BIN=tmpl-linux-arm64   IMAGE=${{ env.IMAGE }}  SUFFIX=-linux-arm64   TARGETPLATFORM=linux/arm64   make image
          docker image ls

      - name: Run image
        run: |
          test_image() { echo "--------------"; echo "Testing: $1"; docker run --rm $1 || exit 1; }
          test_image "${{ env.IMAGE }}:latest-darwin-amd64 --version"
          test_image "${{ env.IMAGE }}:latest-darwin-amd64 --help"
          test_image "${{ env.IMAGE }}:latest-darwin-amd64 generate --help"
          test_image "${{ env.IMAGE }}:latest-darwin-amd64 license"

      - name: Tag commit
        run: |
          docker tag ${{ env.IMAGE }}:latest-darwin-amd64 ${{ env.IMAGE }}:commit-${{ github.sha }}
          docker tag ${{ env.IMAGE }}:latest-darwin-arm64 ${{ env.IMAGE }}:commit-${{ github.sha }}
          docker tag ${{ env.IMAGE }}:latest-linux-amd64  ${{ env.IMAGE }}:commit-${{ github.sha }}
          docker tag ${{ env.IMAGE }}:latest-linux-arm64  ${{ env.IMAGE }}:commit-${{ github.sha }}

      - name: Create multi-platform manifest
        run: |
          docker manifest create \
            ${{ env.IMAGE }}:latest \
            --amend ${{ env.IMAGE }}:latest-darwin-amd64 \
            --amend ${{ env.IMAGE }}:latest-darwin-arm64 \
            --amend ${{ env.IMAGE }}:latest-linux-amd64 \
            --amend ${{ env.IMAGE }}:latest-linux-arm64

      - name: Inspect multi-platform manifest
        run: |
          docker manifest inspect --verbose ${{ env.IMAGE }}:latest

      - name: Login to container registry
        uses: docker/login-action@v3
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          docker push --all-tags ${{ env.IMAGE }}:latest-darwin-amd64
          docker push --all-tags ${{ env.IMAGE }}:latest-darwin-arm64
          docker push --all-tags ${{ env.IMAGE }}:latest-linux-amd64
          docker push --all-tags ${{ env.IMAGE }}:latest-linux-arm64
          docker manifest push ${{ env.IMAGE }}:latest
